// Generated for: bridge 1.0.0.0
// Generated by: Microsoft.JavaScript.NodeApi.Generator 0.9.0.0
/* eslint-disable */


export namespace NativeBridge {
	export function sayHello(name: string): string;
}
