// Generated for: Bridge 1.0.0.0
// Generated by: Microsoft.JavaScript.NodeApi.Generator 0.9.0.0
/* eslint-disable */


export namespace NativeBridge {
	export function sayHello(name: string): string;

	export function getSystemInfo(): string;

	export function getMemoryUsageMB(): number;

	export function getPerformanceInfo(): string;

	export function computeHash(
		input: string,
		algorithm?: string,
	): string;

	export function computeFileHash(
		filePath: string,
		algorithm?: string,
	): string;
}
